name: CI    #workflow

on:   #Triggers: "on pipeline run"
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:                          #Sequência de passos que o job vai seguir
          - uses: actions/checkou t@v3    #Clona o repository na VM
          - name: Set up JDK 17           #Instala o Java 17
            uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'temurin'
          - name: Build and Test
            run: mvn clean verify
